In [1]:
!pip install numpy

In [2]:
import numpy as np

## create array using numpy
## create a 1D array

arr1=np.array([1,2,3,4,5])

print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [25]:
arr2 = np.array([1,2,3,4])

In [5]:
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
arr3=np.array([[1,2,3],[1,2,3],[1,2,3]])

In [14]:
print(arr3)
print(arr3.shape)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
(3, 3)


In [19]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [21]:
np.ones((3,4))
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
## Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
print(arr1)
print(arr2)

[1 2 3 4 5]
[10 20 30 40 50]


In [31]:
## Numpy Vectorization Operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element wise Addition
print("Addition is : ", arr1+arr2)
### Element wise Substraction
print("Substraction: ", arr1-arr2)
### Element wise Division
print("Division is: ", arr1/arr2)


Addition is :  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Division is:  [0.1 0.1 0.1 0.1 0.1]


In [34]:
### Universal Fuction 
arr=np.array([1,2,3,4])
## Sqaure root
print(np.sqrt(arr))
print(np.sin(arr))
print(np.log(arr))
print(np.atleast_2d(arr))
print(np.argsort(arr))

[1.         1.41421356 1.73205081 2.        ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]
[[1 2 3 4]]
[0 1 2 3]


In [38]:
## Array Slicing and Indexing


arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
## Indexing in the Numpy
print(arr[0][0])

1


In [43]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [45]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [46]:
print(arr[0,0])

1


In [47]:
### Modifying arr elements
arr[0,0]=110
print(arr)

[[110   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [51]:
### Statical concept--Normalization
## to have a mean of 0 and std deviation of 1
data = np.array([1,2,3,4,5])

# Calculate the mean and std deviation 
mean=np.mean(data)
std_dev=np.std(data)

# Normalization the data
normalized_data = (data -mean) / std_dev
print("Normalized data:", normalized_data)
print(mean)
print(std_dev)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
3.0
1.4142135623730951
